version: '3'

services:
  db:
    image: postgres
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: "redis:alpine"
    restart: always
    ports:
     - "6379:6379"

  mongodb:
    image: "mongo:3.5"
    environment:
          - MONGO_DATA_DIR=/mongodata/db
          - MONGO_LOG_DIR=/mongodev/null
    volumes:
          - ./mongodata/db:/mongodata/db
  mongo_seed:
    build: ./mongo-seed
    links:
      - mongodb
  # This runs a sandbox worker without a Worker Manger 
  # If the code in a program example hangs thats it
  # That woker is out!
      
  sandbox-python:
    image: mariosky/sandbox-python
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PL=python 
  
  # Please comment those containers you dont need
  sandbox-java:
    image: mariosky/sandbox-java
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PL=java
    
  sandbox-csharp:
    image: mariosky/sandbox-csharp
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PL=csharp
      
  sandbox-perl6:
    image: mariosky/sandbox-java
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PL=perl6
    
  sandbox-golang:
    image: mariosky/sandbox-csharp
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PL=golang

