
version: '3'

# REDIS_HOST Must be the IP Adress of the HOST
# REDIS Server Must be open to other interfaces
services:
  sandbox-python:
    image: mariosky/sandbox-python
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - PL=python

  # Please comment those containers you dont need
  sandbox-java:
    image: mariosky/sandbox-java
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - PL=java

  sandbox-csharp:
    image: mariosky/sandbox-csharp
    command: python3 /home/sandbox/worker.py
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - PL=csharp

  sandbox-perl6:
    image: mariosky/sandbox-java
    command: python /home/sandbox/worker.py
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=6379
      - PL=perl6

#  sandbox-golang:
#    image: mariosky/sandbox-csharp
#    command: python /home/sandbox/worker.py
#    environment:
#      - REDIS_HOST=${REDIS_HOST}
#      - REDIS_PORT=6379
#      - PL=golang