# Generated by Django 2.2.20 on 2021-04-13 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('activitytree', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlesession',
            name='user',
        ),
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='course',
            name='short_description',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='facebook_uid',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='google_uid',
        ),
        migrations.AddField(
            model_name='course',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='lom',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='course',
            name='uri',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='userlearningactivity',
            name='objective_measure',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='userlearningactivity',
            name='objective_status',
            field=models.CharField(default='notSatisfied', max_length=16),
        ),
        migrations.AlterField(
            model_name='userlearningactivity',
            name='progress_status',
            field=models.CharField(default='incomplete', max_length=16),
        ),
        migrations.DeleteModel(
            name='FacebookSession',
        ),
        migrations.DeleteModel(
            name='GoogleSession',
        ),
    ]
