# Generated by Django 2.2.20 on 2021-04-13 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0002_auto_20210413_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='duration',
            field=models.DurationField(default=None, null=True),
        ),
    ]
