# Generated by Django 2.2.20 on 2021-04-14 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0003_course_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='current_price',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
