# Generated by Django 2.2.20 on 2021-04-15 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0004_course_current_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uri',
            field=models.URLField(blank=True, unique=True),
        ),
    ]
