# Generated by Django 2.2.20 on 2021-04-16 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0005_auto_20210415_1832'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='current_price',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='course',
            name='html_description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='lom',
        ),
        migrations.RemoveField(
            model_name='course',
            name='private',
        ),
        migrations.RemoveField(
            model_name='course',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='learningactivity',
            name='description',
        ),
        migrations.RemoveField(
            model_name='learningactivity',
            name='image',
        ),
        migrations.RemoveField(
            model_name='learningactivity',
            name='lom',
        ),
    ]
