# Generated by Django 3.2 on 2021-04-16 19:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0006_auto_20210416_1840'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='meta_data',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='learningactivity',
            name='activity',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='activitytree.jsonactivity'),
        ),
    ]
