# Generated by Django 3.2 on 2021-04-17 00:53

import django.core.serializers.json
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0007_auto_20210416_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='meta_data',
            field=models.JSONField(encoder=django.core.serializers.json.DjangoJSONEncoder, null=True),
        ),
    ]
