# Generated by Django 3.2 on 2021-04-17 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0008_alter_course_meta_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthorLearningActivity',
        ),
    ]
