# Generated by Django 3.2 on 2021-04-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0009_delete_authorlearningactivity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningactivity',
            name='activity',
        ),
        migrations.DeleteModel(
            name='JsonActivity',
        ),
    ]
