# Generated by Django 3.2 on 2021-05-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0012_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='google_scholar',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='linkedin',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
