# Generated by Django 3.2 on 2021-05-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0016_la'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningActivityLocal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('uri', models.URLField(blank=True, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='LA',
        ),
    ]
