# Generated by Django 3.2 on 2021-06-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0018_course_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='_activitytree_course_related_+', to='activitytree.Course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='uri',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
