# Generated by Django 3.2 on 2023-05-31 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activitytree', '0019_auto_20210617_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitytree',
            name='current_activity',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_in', to='activitytree.userlearningactivity'),
        ),
    ]
